### ISSUE TITLE
Find a more elegant way to ask for confirmation

### ISSUE THREAD

**Issue by chrononaut76** [chrononaut76/rails-shopwise#27]
![Screenshot 2024-05-25 at 10 38 04 AM](https://github.com/chrononaut76/rails-shopwise/assets/118705172/7e1db473-2ce7-40c8-9461-0a70e268e035)

[Sweet Alert](https://github.com/carlweis/sweetalert2-rails) maybe?

**Comment by lauradumi** [comment]
this is what it looks like on my end
<img width="1220" alt="Screen Shot 2024-05-25 at 16 40 08" src="https://github.com/chrononaut76/rails-shopwise/assets/154947819/d5f96eee-286d-4c62-8f8e-0788871f0310">
