### ISSUE TITLE
Blank page after logging out, no way to sign up/in

### ISSUE THREAD

**Issue by chrononaut76** [chrononaut76/rails-shopwise#52]
![Screenshot 2024-05-28 at 7 47 30 PM](https://github.com/chrononaut76/rails-shopwise/assets/118705172/a422b6a7-3a1b-4f14-8c79-fde978637318)

**Comment by chrononaut76** [comment]
Options only seen when device is horizontal
![Screenshot 2024-05-28 at 7 49 38 PM](https://github.com/chrononaut76/rails-shopwise/assets/118705172/d35ed46f-6f86-4540-a0f9-f8ac70e66876)

**Comment by DrewGodeke** [comment]
![Screenshot 2024-06-01 150739](https://github.com/chrononaut76/rails-shopwise/assets/155639066/be208f9a-993d-4fef-886a-1e8a89beb376)
